name: CI - Projeto Pesqueiro

# Quando o workflow será executado
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci_pipeline:
    # Equivalente ao executor docker python-env do CircleCI
    runs-on: ubuntu-latest

    steps:
      - name: Rep Checkout
        uses: actions/checkout@v4

      - name: Config Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Job 1: Setup e Instalação (Preparação)
      - name: Setup Poetry Path
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Poetry Install
        run: poetry install

      # Job 2: Verificação de Estilo (Linting)
      - name: Ruff Check
        run: poetry run ruff check .

      # Job 3: Testes Unitários
      - name: Run Pytest
        run: poetry run pytest

      # Job 4: Build (Equivalente ao build_check)
      - name: Poetry Build
        run: poetry build
